### ISSUE TITLE
Server gets SIGKILL and keeps restarting forever

### ISSUE THREAD

**Issue by vmansur** [Jamesits/docker-dst-server#47]
Hello, 
I followed all instructions and installed it in a Ubuntu server  
Docker version 20.10.7, build 20.10.7-0ubuntu1~21.04.2

I used the docker composer file provided in this repo.

Whenever I use `docker-compose up` after setting the token, it gives me this error after a while:

```

dst-server_1  | 2021-11-04 20:16:43,641 INFO success: dst-server-cave entered RUNNING state, process has stayed up for > than 40 seconds (startsecs)
dst-server_1  | 2021-11-04 20:16:45,333 INFO success: dst-server-master entered RUNNING state, process has stayed up for > than 40 seconds (startsecs)
dst-server_1  | 2021-11-04 20:20:42,629 INFO exited: dst-server-master (terminated by SIGKILL; not expected)
dst-server_1  | 2021-11-04 20:20:42,655 INFO spawned: 'dst-server-master' with pid 113
dst-server_1  | [00:00:00]: PersistRootStorage is now /data//DoNotStarveTogether/Cluster_1/Master/
dst-server_1  | [00:00:00]: Starting Up
dst-server_1  | [00:00:00]: Version: 483468
dst-server_1  | [00:00:00]: Current time: Thu Nov  4 20:20:42 2021
[...]
```

And keeps restarting like this for a while 

sometimes I get exceptions: 

```
dst-server_1  | 2021-11-04 20:21:22,764 INFO success: dst-server-master entered RUNNING state, process has stayed up for > than 40 seconds (startsecs)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/log_printer.py", line 217, in watch_events
    for event in event_stream:
  File "/usr/lib/python3/dist-packages/compose/project.py", line 504, in yield_loop
    yield build_container_event(event)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 472, in build_container_event
    container = Container.from_id(self.client, event['id'])
  File "/usr/lib/python3/dist-packages/compose/container.py", line 48, in from_id
    return cls(client, client.inspect_container(id), has_been_inspected=True)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 758, in inspect_container
    self._get(self._url("/containers/{0}/json", container)), True
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

**Comment by Jamesits** [comment]
Please post outputs of `lscpu` and `free -wh`. Also please check `dmesg` and see if there are any error messages.

**Comment by vmansur** [comment]
lscpu:

```
 lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      7
Model:                           85
Model name:                      DO-Premium-Intel
Stepping:                        7
CPU MHz:                         2494.144
BogoMIPS:                        4988.28
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        4 MiB
NUMA node0 CPU(s):               0
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx pdpe1gb rdtscp lm arch_perfmon
                                  nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rd
                                 rand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept
                                 _ad fsgsbase bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec x
                                 getbv1 pku ospke avx512_vnni arch_capabilities
```

free -wh

```

free -wh
              total        used        free      shared     buffers       cache   available
Mem:          972Mi       193Mi       158Mi       0.0Ki        14Mi       605Mi       625Mi
Swap:            0B          0B          0B

```

Dmesg: 

```
[  870.643587] docker-compose invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[  870.643605] CPU: 0 PID: 2676 Comm: docker-compose Not tainted 5.11.0-38-generic #42-Ubuntu
[  870.643609] Hardware name: DigitalOcean Droplet, BIOS 20171212 12/12/2017
[  870.643615] Call Trace:
[  870.643629]  show_stack+0x52/0x58
[  870.643674]  dump_stack+0x70/0x8b
[  870.643683]  dump_header+0x4f/0x1f6
[  870.643693]  oom_kill_process.cold+0xb/0x10
[  870.643701]  out_of_memory.part.0+0xcc/0x280
[  870.643719]  out_of_memory+0x41/0x80
[  870.643721]  __alloc_pages_slowpath.constprop.0+0x95a/0xa20
[  870.643732]  __alloc_pages_nodemask+0x2e0/0x310
[  870.643735]  alloc_pages_current+0x87/0x110
[  870.643742]  pagecache_get_page+0x18a/0x3b0
[  870.643754]  filemap_fault+0x589/0x840
[  870.643758]  ? filemap_map_pages+0x215/0x3f0
[  870.643762]  ext4_filemap_fault+0x32/0x50
[  870.643783]  __do_fault+0x3c/0xe0
[  870.643788]  do_fault+0xc4/0x1f0
[  870.643792]  handle_pte_fault+0x1e5/0x260
[  870.643796]  __handle_mm_fault+0x59a/0x7c0
[  870.643801]  handle_mm_fault+0xd7/0x2b0
[  870.643805]  do_user_addr_fault+0x1a0/0x450
[  870.643820]  exc_page_fault+0x69/0x150
[  870.643834]  ? asm_exc_page_fault+0x8/0x30
[  870.643843]  asm_exc_page_fault+0x1e/0x30
[  870.643848] RIP: 0033:0x5012c0
[  870.643862] Code: Unable to access opcode bytes at RIP 0x501296.
[  870.643863] RSP: 002b:00007fff29126798 EFLAGS: 00010246
[  870.643867] RAX: 000000000090c980 RBX: 0000000000000001 RCX: 0000000000000011
[  870.643869] RDX: 00000000028039d0 RSI: 0000000000000001 RDI: 00007fac274edb40
[  870.643871] RBP: 00007fff29126820 R08: 00007fac274edb40 R09: 0000000000000c30
[  870.643873] R10: 00007fac274d4000 R11: 000000000001e150 R12: 00007fac274d4e80
[  870.643874] R13: 00007fac274e1a30 R14: 00007fac28863bf0 R15: 00007fac274ff080
[  870.643879] Mem-Info:
[  870.643887] active_anon:336 inactive_anon:207844 isolated_anon:0
                active_file:91 inactive_file:64 isolated_file:0
                unevictable:4865 dirty:0 writeback:0
                slab_reclaimable:5135 slab_unreclaimable:9813
                mapped:2425 shmem:264 pagetables:1542 bounce:0
                free:12510 free_pcp:102 free_cma:0
[  870.643894] Node 0 active_anon:1344kB inactive_anon:831376kB active_file:364kB inactive_file:256kB unevictable:19460kB isolated(anon):0kB isolated(file):0kB mapped:9700kB dirty:0kB writeback:0kB shmem:1056kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB kernel_stack:4048kB pagetables:6168kB all_unreclaimable? no
[  870.643900] Node 0 DMA free:4424kB min:748kB low:932kB high:1116kB reserved_highatomic:0KB active_anon:0kB inactive_anon:10968kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[  870.643906] lowmem_reserve[]: 0 920 920 920 920
[  870.643912] Node 0 DMA32 free:45616kB min:44304kB low:55380kB high:66456kB reserved_highatomic:2048KB active_anon:1344kB inactive_anon:820408kB active_file:364kB inactive_file:256kB unevictable:19460kB writepending:0kB present:1032172kB managed:979676kB mlocked:19460kB bounce:0kB free_pcp:408kB local_pcp:408kB free_cma:0kB
[  870.643918] lowmem_reserve[]: 0 0 0 0 0
[  870.643923] Node 0 DMA: 4*4kB (UM) 1*8kB (U) 3*16kB (UE) 4*32kB (UME) 4*64kB (UE) 1*128kB (U) 3*256kB (UME) 2*512kB (UE) 2*1024kB (ME) 0*2048kB 0*4096kB = 4424kB
[  870.643943] Node 0 DMA32: 727*4kB (UMEH) 592*8kB (UMEH) 395*16kB (UMEH) 190*32kB (UMEH) 82*64kB (UMEH) 43*128kB (UEH) 14*256kB (UME) 4*512kB (UE) 7*1024kB (ME) 1*2048kB (U) 0*4096kB = 45644kB
[  870.643970] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=1048576kB
[  870.643973] Node 0 hugepages_total=0 hugepages_free=0 hugepages_surp=0 hugepages_size=2048kB
[  870.643975] 2705 total pagecache pages
[  870.643977] 0 pages in swap cache
[  870.643978] Swap cache stats: add 0, delete 0, find 0/0
[  870.643980] Free swap  = 0kB
[  870.643981] Total swap = 0kB
[  870.643982] 262041 pages RAM
[  870.643983] 0 pages HighMem/MovableOnly
[  870.643984] 13145 pages reserved
[  870.643985] 0 pages hwpoisoned
[  870.643986] Tasks state (memory values in pages):
[  870.643990] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[  870.644012] [    335]     0   335     7982      907    86016        0          -250 systemd-journal
[  870.644018] [    452]     0   452    70285     4735    94208        0         -1000 multipathd
[  870.644022] [    491]   102   491    22106      307    81920        0             0 systemd-timesyn
[  870.644025] [    532]   100   532     4036      591    73728        0             0 systemd-network
[  870.644029] [    551]   101   551     6030     1656    90112        0             0 systemd-resolve
[  870.644032] [    575]     0   575     4982      525    57344        0         -1000 systemd-udevd
[  870.644036] [    630]     0   630    59930      429    90112        0             0 accounts-daemon
[  870.644039] [    633]     0   633     2186      523    49152        0             0 cron
[  870.644042] [    634]   103   634     2144      776    53248        0          -900 dbus-daemon
[  870.644045] [    637]     0   637   306402      180   147456        0          -900 droplet-agent
[  870.644049] [    641]     0   641     7883     3004   102400        0             0 networkd-dispat
[  870.644052] [    643]   104   643    55304      753    69632        0             0 rsyslogd
[  870.644055] [    647]     0   647     3456      277    65536        0             0 systemd-logind
[  870.644058] [    650]     0   650    98438      771   122880        0             0 udisksd
[  870.644061] [    661]     0   661   336269     3589   278528        0          -999 containerd
[  870.644064] [    665]     0   665     1879      475    49152        0             0 agetty
[  870.644067] [    674]     0   674     1498      383    49152        0             0 agetty
[  870.644069] [    705]     0   705     3323      735    65536        0         -1000 sshd
[  870.644072] [    706]     0   706    58747      630    86016        0             0 polkitd
[  870.644075] [    796]     0   796    27343     2921   110592        0             0 unattended-upgr
[  870.644078] [   1008]     0  1008     3719      673    69632        0             0 sshd
[  870.644081] [   1071]     0  1071   202147     9960   376832        0          -500 dockerd
[  870.644084] [   1200]     0  1200     3842     1008    73728        0             0 systemd
[  870.644087] [   1202]     0  1202    25497      839    90112        0             0 (sd-pam)
[  870.644090] [   1438]     0  1438     2647      968    57344        0             0 bash
[  870.644093] [   1864]     0  1864   161254     3762   221184        0          -900 snapd
[  870.644096] [   2676]     0  2676    84541     6758   143360        0             0 docker-compose
[  870.644099] [   2700]     0  2700   118632      106   110592        0          -500 docker-proxy
[  870.644102] [   2705]     0  2705   118632      104   114688        0          -500 docker-proxy
[  870.644105] [   2718]     0  2718   118632      105   114688        0          -500 docker-proxy
[  870.644108] [   2723]     0  2723   118632      106   118784        0          -500 docker-proxy
[  870.644111] [   2736]     0  2736   118632      104   118784        0          -500 docker-proxy
[  870.644114] [   2741]     0  2741   118632      105   110592        0          -500 docker-proxy
[  870.644117] [   2754]     0  2754   118632      103   110592        0          -500 docker-proxy
[  870.644124] [   2759]     0  2759   118632      104   106496        0          -500 docker-proxy
[  870.644127] [   2772]     0  2772   118632      105   114688        0          -500 docker-proxy
[  870.644130] [   2777]     0  2777   118632      105   114688        0          -500 docker-proxy
[  870.644133] [   2791]     0  2791   177877      602   110592        0          -998 containerd-shim
[  870.644136] [   2809]     0  2809     1134       16    57344        0             0 s6-svscan
[  870.644139] [   2863]     0  2863     1136       17    57344        0             0 s6-supervise
[  870.644142] [   2864]     0  2864     1136       17    49152        0             0 s6-supervise
[  870.644145] [   2866]  1000  2866   185213   150902  1429504        0             0 dontstarve_dedi
[  870.644148] [   3028]     0  3028     3718      878    65536        0             0 sshd
[  870.644151] [   3095]     0  3095     2647      882    61440        0             0 bash
[  870.644154] [   3156]     0  3156     3057      628    53248        0             0 cron
[  870.644159] [   3157]     0  3157      658      165    40960        0             0 sh
[  870.644162] [   3158]     0  3158      630      172    45056        0             0 run-parts
[  870.644165] [   3159]     0  3159      658      165    40960        0             0 droplet-agent
[  870.644168] [   3160]     0  3160     2246      458    53248        0             0 bash
[  870.644171] [   3162]     0  3162     4411      920    77824        0             0 apt-get
[  870.644173] [   3198]     0  3198     4411      412    77824        0             0 apt-get
[  870.644176] [   3207]     0  3207    74457     1431   163840        0             0 packagekitd
[  870.644179] [   3217]     0  3217      658      165    45056        0             0 sh
[  870.644182] [   3218]     0  3218      658      407    45056        0             0 update-motd-upd
[  870.644185] [   3232]     0  3232    32494    17544   286720        0             0 apt-check
[  870.644189] [   3240]     0  3240     2371      778    57344        0             0 htop
[  870.644191] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/docker/c8d1828156e3ad2f5d4b1991005b075e5ec8e61c1947b3cb4940202b4d4887b7,task=dontstarve_dedi,pid=2866,uid=1000
[  870.644237] Out of memory: Killed process 2866 (dontstarve_dedi) total-vm:740852kB, anon-rss:603608kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1396kB oom_score_adj:0
[  870.743938] oom_reaper: reaped process 2866 (dontstarve_dedi), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

```


Seems to be an oom error. 
Which is weird because another docker image works (not as configurable as this one) and also installing the server manually in the instance also works with 40% free memory...

**Comment by Jamesits** [comment]
Maybe it is because this docker container starts 2 server instances (overworld + caves) by default. To reduce the memory, try the following procedure:

First download https://github.com/Jamesits/docker-dst-server/blob/master/supervisor/supervisor.conf to your machine, remove section `[program:dst-server-cave]`; set `programs=dst-server-master` under `[group:dst-server]`. 

Then launch the container with additional argument `-v path/to/new/supervisor.conf:/etc/supervisor/supervisor.conf`.

**Comment by vmansur** [comment]
Thank you will try that!

**Comment by RoderickXiang** [comment]
I also have this problem,it seems like oom error.
I solve the problem by turn of other docker container I don't use.😁
